name: bergamot_translator_example
description: "Demonstrates how to use the bergamot_translator plugin."
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  bergamot_translator:
    path: ../

  cupertino_icons: ^1.0.8

  archive: ^4.0.7
  http: ^1.6.0
  logging: ^1.3.0
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - assets/models/zh_en
  #   - assets/models/en_zh
